### ISSUE TITLE
Invalid file/directory names

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot-usecases-output#1]
Hi @jesus-gorronogoitia , there is an issue with a few file names being invalid on Windows, so the repo can't be cloned on Windows. Seems to be the colon character (':'). Could you fix this?

From Git log:
error: unable to create file atos/supersede/2018-02-19_16-32-07/dspot_if_2018-02-19_16:32:07.txt: Invalid argument
error: unable to create file atos/supersede/2018-02-19_16-32-07/dspot_if_stats_2018-02-19_16:32:07.txt: Invalid argument
fatal: cannot create directory at 'atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier': Invalid argument

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye , fixed, please try it again

**Comment by ltboye** [comment]
Thank you @jesus-gorronogoitia , it's fine now.
